esphome:
  name: powerpal-gateway
  friendly_name: Powerpal Gateway

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_MBEDTLS_CERTIFICATE_BUNDLE: y
      CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL: y

external_components:
  - source:
      type: git
      url: https://github.com/gurrier/esphome-powerpal_ble.git
      ref: "1.2"   # or “main” for bleeding edge
    components: [ powerpal_ble ]

time:
  - platform: homeassistant
    id: homeassistant_time

ble_client:
  - mac_address: !secret powerpal_mac_address # A1:B2:C3:D4:E5:F6 Your Powerpal MAC ADDRESS
    id: powerpal

button:
  - platform: restart
    name: "Restart"
    icon: "mdi:restart"

sensor:
  - platform: powerpal_ble
    id: powerpal_ble_sensor
    ble_client_id: powerpal
    power:
      name: "Powerpal Power"
    battery_level:
      name: "Powerpal Battery"
    daily_energy:
      name: "Powerpal Daily Energy"
    daily_pulses:
      name: "Powerpal Daily Pulses"
    energy:
      name: "Powerpal Total Energy"
    watt_hours:
      name: "Powerpal Watt Hours"
    pulses:
      name: "Powerpal Pulses"
    timestamp:
      name: "Powerpal Timestamp"
    cost:
      name: "Powerpal Cost"
    pairing_code: !secret powerpal_pairing_code #123456 PUT THE 6 digit PAIRING CODE FOUND WITH YOUR POWERPAL HERE 
    notification_interval: 1 # In seconds
    pulses_per_kwh: 1000
    time_id: homeassistant_time
    powerpal_cloud_uploader: true # set to true to upload data to Powerpal
    cost_per_kwh: 0.20 # dollars per kWh (optional)
    
logger:
#  level: DEBUG
#  logs:
#    powerpal_ble: DEBUG

api:
  encryption:
    key: !secret esphome_api_encryption_key

ota:
  platform: esphome
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Powerpal Fallback Hotspot"
    password: !secret fallback_password

web_server:
  port: 80
  auth:
    username: !secret esphome_web_username
    password: !secret esphome_web_password
